In [123]:
"""
层次分析法
"""
import numpy as np
import typing as ty


In [124]:
A = np.array([[1,1/2,4,3,3],[2,1,7,5,5],[1/4,1/7,1,1/2,1/3],[1/3,1/5,2,1,1],[1/3,1/5,3,1,1]])
HuaFei = np.array([[1,1/3,1/8],[3,1,1/3],[8,3,1]])
JuZhu = np.array([[1,1,3],[1,1,3],[1/3,1/3,1]])
YinShi = np.array([[1,3,4],[1/3,1,1],[1/4,1,1]])
JiaoTong = np.array([[1,1,1/4],[1,1,1/4],[4,4,1]])
JingSe = np.array([[1,2,5],[1/2,1,2],[1/5,1/2,1]])

In [125]:
"""
一致性检验
"""
RI=[0,0,0.52,0.89,1.12,1.26,1.36,1.41,1.46,1.49,1.52,1.54,1.56,1.58,1.59]
def check_consistency(A:np.array):
    eigenvalue, _ = np.linalg.eig(A)
    CI = (max(eigenvalue)-A.shape[0])/(A.shape[0]-1)
    CR = CI/RI[A.shape[0]]
    print(f"矩阵的CI:{CI},CR:{CR}",end="--->")
    if(CR<0.1):
        print(f"通过一致性检验")
    else:
        print(f"不通过一致性检验")

print("A:",end="")
check_consistency(A)
print("HuaFei:",end="")
check_consistency(HuaFei)
print("JuZhu:",end="")
check_consistency(JuZhu)
print("YinShi:",end="")
check_consistency(YinShi)
print("JiaoTong:",end="")
check_consistency(JiaoTong)
print("JingSe:",end="")
check_consistency(JingSe)

A:矩阵的CI:(0.018021102142554035+0j),CR:(0.014302462017900027+0j)--->通过一致性检验
HuaFei:矩阵的CI:(0.0007708125321126413+0j),CR:(0.0008660814967557768+0j)--->通过一致性检验
JuZhu:矩阵的CI:-4.440892098500626e-16,CR:-4.989766402809693e-16--->通过一致性检验
YinShi:矩阵的CI:(0.00460135635713943+0j),CR:(0.005170063322628573+0j)--->通过一致性检验
JiaoTong:矩阵的CI:0.0,CR:0.0--->通过一致性检验
JingSe:矩阵的CI:(0.0027675558692488167+0j),CR:(0.003109613336234626+0j)--->通过一致性检验


In [126]:
"""
判别矩阵求权重
"""
def method1(V:np.array):
    """算术平均法"""
    A = np.copy(V)
    # print("算术平均法:",end="")
    tmp = np.sum(A,axis=0)
    for i in range(A.shape[0]):
        for j in range(A.shape[1]):
            A[i][j] /= tmp[j]
    B = np.sum(A,axis=1)
    B /= A.shape[0]
    return(B)

def method2(V:np.array):
    """几何平均法"""
    A = np.copy(V)
    # print("几何平均法:",end="")
    tmp = []
    FenMu = 0
    for i in range(A.shape[0]):
        mat=1
        for j in range(A.shape[1]):
            mat*=A[i][j]
        FenMu+=mat**(1/A.shape[0])
        tmp.append(mat**(1/A.shape[0]))
    tmp/=FenMu
    return(tmp)

def method3(V:np.array):
    """特征值法"""
    A = np.copy(V)
    # print("特征值法:",end="")
    B = np.linalg.eig(A)
    index = np.argmax(B[0])
    lamda_max = np.real(B[0][index])
    vector = B[1][:,index]
    vector_final = np.transpose((np.real(vector)))
    # print(f'最大特征值为：{lamda_max}\n        对应的特征向量：{vector_final}')
    return(vector_final/np.sum(vector_final))
print(method1(JingSe))
print(method2(JingSe))
print(method3(JingSe))

[0.59488796 0.27661064 0.1285014 ]
[0.59537902 0.27635046 0.12827052]
[0.59537902 0.27635046 0.12827052]


In [127]:
"""
汇总结果得到权重矩阵
"""
method3(A)
SuHang = []
BeiDaiHe = []
GuiLin = []
SuHang.append(method3(JingSe)[0])
SuHang.append(method3(HuaFei)[0])
SuHang.append(method3(JuZhu)[0])
SuHang.append(method3(YinShi)[0])
SuHang.append(method3(JiaoTong)[0])
BeiDaiHe.append(method3(JingSe)[1])
BeiDaiHe.append(method3(HuaFei)[1])
BeiDaiHe.append(method3(JuZhu)[1])
BeiDaiHe.append(method3(YinShi)[1])
BeiDaiHe.append(method3(JiaoTong)[1])
GuiLin.append(method3(JingSe)[2])
GuiLin.append(method3(HuaFei)[2])
GuiLin.append(method3(JuZhu)[2])
GuiLin.append(method3(YinShi)[2])
GuiLin.append(method3(JiaoTong)[2])
SuHang = np.array(SuHang)
BeiDaiHe = np.array(BeiDaiHe)
GuiLin = np.array(GuiLin)
print(SuHang)
print(BeiDaiHe)
print(GuiLin)


[0.59537902 0.08193475 0.42857143 0.63370792 0.16666667]
[0.27635046 0.2363407  0.42857143 0.19192062 0.16666667]
[0.12827052 0.68172455 0.14285714 0.17437146 0.66666667]


In [128]:
"""
计算各个方案得分
"""
print(method3(A)@SuHang)
print(method3(A)@BeiDaiHe)
print(method3(A)@GuiLin)

0.2992545297453049
0.24530398001537007
0.4554414902393249
